/**
 * The site is deployed under a base path (/portfolio). Every internal URL must
 * go through here — a hard-coded leading "/" 404s on GitHub Pages, which is the
 * single most common way this deploy breaks.
 */
const BASE = import.meta.env.BASE_URL.replace(/\/$/, '');

export function url(path: string): string {
  if (/^(https?:|mailto:|tel:|#)/.test(path)) return path;
  const clean = path.startsWith('/') ? path : `/${path}`;
  return `${BASE}${clean}`;
}

/**
 * Optimised derivatives of a public image, generated by scripts/optimize-images.mjs.
 * Falls back to the original when the path is not one of the managed folders.
 */
export function imageSet(src: string): { src: string; srcset?: string } {
  const match =
    src.match(/^\/images\/(thumbs|fulls)\/(.+)\.(jpe?g|png)$/i) ??
    src.match(/^\/images\/()(avatar)\.jpg$/i);
  if (!match) return { src: url(encodeURI(src)) };

  const folder = match[1] || 'root';
  const name = match[2];
  const at = (w: number) =>
    url(encodeURI(`/images/opt/${folder}/${name}-${w}.webp`));

  return { src: at(800), srcset: `${at(800)} 800w, ${at(1600)} 1600w` };
}

/**
 * Where an index row points. An http(s) destination is left alone; an image
 * path resolves to the largest derivative, because the originals are not
 * deployed.
 */
export function resolveDestination(destination: string): string {
  if (/^https?:/.test(destination)) return destination;
  const set = imageSet(destination);
  return set.srcset ? (set.srcset.split(' ').at(-2) ?? set.src) : set.src;
}

/** True for links that leave the site — used to tag outbound_click events. */
export function isExternal(href: string): boolean {
  return /^https?:\/\//.test(href) && !href.includes('lamkenneth89.github.io');
}

export function domainOf(href: string): string {
  try {
    return new URL(href).hostname.replace(/^www\./, '');
  } catch {
    return '';
  }
}
